---

# 'hosting_infrastructure' is used to drive the correct behavior based
# on the hosting infrastructure, cloud provider, etc. Valid values are:
# - 'openstack'
# - 'aws'
# - 'azure' (Coming Soon)
# - 'gcp'
hosting_infrastructure: libvirt

# Cluster Environment ID to uniquely identify the environment
env_id: env1

ansible_user: root
ansible_become: true

dns_domain: "myorg.com"

docker_storage_block_device: "/dev/vdb"

# Subscription Management Details
rhsm_register: True
rhsm_repos:
 - "rhel-7-server-rpms"
 - "rhel-7-server-ose-3.10-rpms"
 - "rhel-7-server-extras-rpms"
 - "rhel-7-fast-datapath-rpms"
 - "rhel-7-server-ansible-2.4-rpms"

# Use RHSM username, password and optionally pool:
# NOTE:
# by default define the environment variables RHSM_USERNAME and RHSM_PASSWORD
# use the -e option to specify on CLI instead of statically set here
rhsm_username: "{{ lookup('env', 'RHSM_USER' )}}"
rhsm_password: "{{ lookup('env', 'RHSM_PASSWD' )}}"

# leave commented out if you want to `--auto-attach` a pool
#rhsm_pool: "{{ lookup('env', 'RHSM_POOL' )}}"
