---
libvirt_name: "master"
libvirt_title: "Master"
libvirt_description: "Master"
libvirt_memory: "2048"
libvirt_vcpus: "1"
libvirt_disk_size: "15"
libvirt_os_variant: "rhel7"
libvirt_iso: "/home/abhishek/Downloads/rhel-server-7.5-x86_64-dvd.iso"
libvirt_ksfile: "/home/abhishek/research/casl-ansible/inventory/sample.libvirt.example.com.d/files/ks/master.ks"
libvirt_network_hostif: "virbr0"
libvirt_http_host: '192.168.122.1'
libvirt_network_type: "bridge"

infra: cloud-host.local.yml
ansible_host: 192.168.122.10
ansible_user: root
ansible_ssh_pass: redhat
